/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traintickets.userinterface;

/**
 *
 * @author koumudi
 */
public class AdminFunctions extends javax.swing.JFrame {

    /**
     * Creates new form AdminFunctions
     */
    public AdminFunctions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addUserBtn = new javax.swing.JButton();
        resetPwdBtn = new javax.swing.JButton();
        addStationBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        rmvUserBtn = new javax.swing.JButton();
        rmvStationBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        addUserBtn.setBackground(new java.awt.Color(0, 153, 153));
        addUserBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addUserBtn.setText("Add User");
        addUserBtn.setActionCommand("Show Data");
        addUserBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });

        resetPwdBtn.setBackground(new java.awt.Color(0, 153, 153));
        resetPwdBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        resetPwdBtn.setText("Reset Password");
        resetPwdBtn.setActionCommand("Show Data");
        resetPwdBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetPwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPwdBtnActionPerformed(evt);
            }
        });

        addStationBtn.setBackground(new java.awt.Color(0, 153, 153));
        addStationBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addStationBtn.setText("Add Station");
        addStationBtn.setActionCommand("Show Data");
        addStationBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addStationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStationBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(0, 153, 153));
        logoutBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setActionCommand("Show Data");
        logoutBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        rmvUserBtn.setBackground(new java.awt.Color(0, 153, 153));
        rmvUserBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rmvUserBtn.setText("Remove User");
        rmvUserBtn.setActionCommand("Show Data");
        rmvUserBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rmvUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmvUserBtnActionPerformed(evt);
            }
        });

        rmvStationBtn.setBackground(new java.awt.Color(0, 153, 153));
        rmvStationBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rmvStationBtn.setText("Remove Station");
        rmvStationBtn.setActionCommand("Show Data");
        rmvStationBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rmvStationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmvStationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addStationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(rmvUserBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rmvStationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resetPwdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(addUserBtn)
                .addGap(30, 30, 30)
                .addComponent(rmvUserBtn)
                .addGap(30, 30, 30)
                .addComponent(addStationBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(rmvStationBtn)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBtn)
                    .addComponent(resetPwdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        // TODO add your handling code here:
        AddUserForm addUser = new AddUserForm(this);
        addUser.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_addUserBtnActionPerformed

    private void resetPwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPwdBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetPwdBtnActionPerformed

    private void addStationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStationBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStationBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void rmvUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmvUserBtnActionPerformed

    private void rmvStationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvStationBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmvStationBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStationBtn;
    private javax.swing.JButton addUserBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton resetPwdBtn;
    private javax.swing.JButton rmvStationBtn;
    private javax.swing.JButton rmvUserBtn;
    // End of variables declaration//GEN-END:variables
}
