/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traintickets.userinterface;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Sanduni Alwis
 */
public class UserFunctions extends javax.swing.JFrame {

    /**
     * Creates new form functions
     */
    public UserFunctions() {
        initComponents();
        setResizable(false);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enterDataButton = new javax.swing.JButton();
        showDataButton = new javax.swing.JToggleButton();
        summaryButton = new javax.swing.JButton();
        printDataButton = new javax.swing.JButton();
        resetPwdBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        enterDataButton.setBackground(new java.awt.Color(0, 153, 153));
        enterDataButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        enterDataButton.setText("Enter Data");
        enterDataButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enterDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterDataButtonActionPerformed(evt);
            }
        });
        enterDataButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterDataButtonKeyPressed(evt);
            }
        });

        showDataButton.setBackground(new java.awt.Color(0, 153, 153));
        showDataButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        showDataButton.setText("Show Data");
        showDataButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        showDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDataButtonActionPerformed(evt);
            }
        });
        showDataButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                showDataButtonKeyPressed(evt);
            }
        });

        summaryButton.setBackground(new java.awt.Color(0, 153, 153));
        summaryButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        summaryButton.setText("Summary");
        summaryButton.setActionCommand("Show Data");
        summaryButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        summaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryButtonActionPerformed(evt);
            }
        });

        printDataButton.setBackground(new java.awt.Color(0, 153, 153));
        printDataButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        printDataButton.setText("Print Data");
        printDataButton.setActionCommand("Show Data");
        printDataButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        printDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printDataButtonActionPerformed(evt);
            }
        });

        resetPwdBtn.setBackground(new java.awt.Color(0, 153, 153));
        resetPwdBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        resetPwdBtn.setText("Reset Password");
        resetPwdBtn.setActionCommand("Show Data");
        resetPwdBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetPwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPwdBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(0, 153, 153));
        logoutBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setActionCommand("Show Data");
        logoutBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(printDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(summaryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(enterDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resetPwdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(enterDataButton)
                .addGap(42, 42, 42)
                .addComponent(showDataButton)
                .addGap(43, 43, 43)
                .addComponent(summaryButton)
                .addGap(41, 41, 41)
                .addComponent(printDataButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBtn)
                    .addComponent(resetPwdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterDataButtonActionPerformed
        // TODO add your handling code here:
        Selection select = new Selection(this);
        select.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_enterDataButtonActionPerformed

    private void showDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDataButtonActionPerformed
        // TODO add your handling code here:
        ShowDataFunctions showSelection = new ShowDataFunctions(this);
        showSelection.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_showDataButtonActionPerformed

    private void summaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryButtonActionPerformed
        // TODO add your handling code here:
        ShowDataFunctions showSelection = new ShowDataFunctions(this);
        showSelection.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_summaryButtonActionPerformed

    private void printDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDataButtonActionPerformed
        // TODO add your handling code here:
        ShowDataFunctions showSelection = new ShowDataFunctions(this);
        showSelection.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_printDataButtonActionPerformed

    private void enterDataButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterDataButtonKeyPressed
        // TODO add your handling code here:     
    }//GEN-LAST:event_enterDataButtonKeyPressed

    private void showDataButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showDataButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_showDataButtonKeyPressed

    private void printDataButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDataButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printDataButton3ActionPerformed

    private void resetPwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPwdBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetPwdBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterDataButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton printDataButton;
    private javax.swing.JButton resetPwdBtn;
    private javax.swing.JToggleButton showDataButton;
    private javax.swing.JButton summaryButton;
    // End of variables declaration//GEN-END:variables
}
