/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package traintickets.userinterface.user;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author USER
 */
public class ShowDataFunctions extends javax.swing.JFrame {

    /** Creates new form showSelect */
    public ShowDataFunctions(JFrame parent) {
        initComponents();
        this.parent = parent;
        Toolkit toolkit = getToolkit();
        setResizable(false);
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        overallBtn = new javax.swing.JButton();
        monthlyStation = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        overallBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        overallBtn.setText("Overall");
        overallBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        overallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overallBtnActionPerformed(evt);
            }
        });
        overallBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                overallBtnKeyPressed(evt);
            }
        });

        monthlyStation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        monthlyStation.setText("Monthly Station ");
        monthlyStation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monthlyStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyStationActionPerformed(evt);
            }
        });
        monthlyStation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                monthlyStationKeyPressed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        backButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(monthlyStation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overallBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(monthlyStation)
                .addGap(18, 18, 18)
                .addComponent(overallBtn)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void overallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overallBtnActionPerformed
        // TODO add your handling code here:
        getOverallStatisticsSelection();
        
    }//GEN-LAST:event_overallBtnActionPerformed

    private void monthlyStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyStationActionPerformed
        // TODO add your handling code here:
                getMonthlyOverallDataOfStation();

    }//GEN-LAST:event_monthlyStationActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        backButtonFunction();
    }//GEN-LAST:event_backButtonActionPerformed

    private void monthlyStationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthlyStationKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== java.awt.event.KeyEvent.VK_ENTER){ 
            getMonthlyOverallDataOfStation();
        }
    }//GEN-LAST:event_monthlyStationKeyPressed

    private void backButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backButtonKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== java.awt.event.KeyEvent.VK_ENTER){ 
            backButtonFunction();
        }
        
    }//GEN-LAST:event_backButtonKeyPressed

    private void overallBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_overallBtnKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== java.awt.event.KeyEvent.VK_ENTER){ 
            getOverallStatisticsSelection();
        }
        
    }//GEN-LAST:event_overallBtnKeyPressed

   private void getMonthlyOverallDataOfStation(){
        StationDataFilter select = new StationDataFilter(this);
        select.setVisible(true);
        setVisible(false);
   }
   
   private void getOverallStatisticsSelection(){
        OverallStatSelection statSelection = new OverallStatSelection(this);
        statSelection.setVisible(true);
        setVisible(false);
   }
    
    private void backButtonFunction(){
        parent.setVisible(true);
        dispose();
    }
    private JFrame parent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton monthlyStation;
    private javax.swing.JButton overallBtn;
    // End of variables declaration//GEN-END:variables

}
