/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traintickets;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static traintickets.userinterface.Selection.codetxt;

/**
 *
 * @author USER
 */
public class monthlyStation extends javax.swing.JFrame {

    /**
     * Creates new form monthlyStation
     */
    public monthlyStation() {
        initComponents();
        setResizable(true);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();

        int xsize = (int) toolkit.getScreenSize().getWidth();
        int ysize = (int) toolkit.getScreenSize().getHeight();
        this.setSize(xsize, ysize);

        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

         if ("ABA".equals(monthStatSelect.codetxt.getText()) | "aba".equals(monthStatSelect.codetxt.getText())) {

            jTextField1.setText("Ambalangoda");

        }
        String year = monthStatSelect.yeartxt.getValue().toString();
        jTextField2.setText(year);
        String month = monthStatSelect.monthtxt.getValue().toString();
        jTextField3.setText(month);
   


        show_station();
    }

    public ArrayList<Station> stationList() {
        ArrayList<Station> stationList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3307/odemetrics", "root", "");
            String sql1 = "Select * from `table_demo`";
            Statement st = con1.createStatement();
            ResultSet rs = st.executeQuery(sql1);
            Station station;
            while (rs.next()) {
                station = new Station(rs.getString("stcode"), rs.getString("name"), rs.getInt("first_cls"), rs.getInt("second_cls"), rs.getInt("third_cls_A"), rs.getInt("third_cls_B"), rs.getInt("third_cls_C"), rs.getInt("total"));
                stationList.add(station);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return stationList;

    }

    public void show_station() {
        ArrayList<Station> list = stationList();
        DefaultTableModel model = (DefaultTableModel) display_table.getModel();
        Object[] row = new Object[8];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getstcode();
            row[1] = list.get(i).getname();
            row[2] = list.get(i).getfirst_cls();
            row[3] = list.get(i).getsecond_cls();
            row[4] = list.get(i).getthird_cls_A();
            row[5] = list.get(i).getthird_cls_B();
            row[6] = list.get(i).getthird_cls_C();
            row[7] = list.get(i).gettotal();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_table = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jScrollPane1.setBackground(new java.awt.Color(51, 204, 255));

        display_table.setAutoCreateRowSorter(true);
        display_table.setBackground(new java.awt.Color(0, 204, 204));
        display_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255)));
        display_table.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        display_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "stcode", "name", "first_cls", "second_cls", "third_cls_A", "third_cls_B", "third_cls_C", "total"
            }
        ));
        display_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        display_table.setCellSelectionEnabled(true);
        display_table.setEditingRow(1);
        display_table.setGridColor(new java.awt.Color(0, 102, 102));
        display_table.setMaximumSize(new java.awt.Dimension(2147483647, 1500));
        display_table.setMinimumSize(new java.awt.Dimension(1000, 64));
        display_table.setPreferredSize(new java.awt.Dimension(1400, 700));
        display_table.setShowGrid(true);
        jScrollPane1.setViewportView(display_table);
        display_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(820, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(109, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(417, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addGap(86, 86, 86)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable display_table;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
