/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package traintickets;

import traintickets.userinterface.Functions;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author USER
 */
public class showSelect extends javax.swing.JFrame {

    /** Creates new form showSelect */
    public showSelect(JFrame parent) {
        initComponents();
        this.parent = parent;
        Toolkit toolkit = getToolkit();
        setResizable(false);
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        monthlyOverall = new javax.swing.JButton();
        monthlyStation = new javax.swing.JButton();
        annuallyOverall = new javax.swing.JButton();
        annuallyStation = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        monthlyOverall.setBackground(new java.awt.Color(0, 204, 204));
        monthlyOverall.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        monthlyOverall.setText("Monthly Overall");
        monthlyOverall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyOverallActionPerformed(evt);
            }
        });

        monthlyStation.setBackground(new java.awt.Color(0, 204, 204));
        monthlyStation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        monthlyStation.setText("Monthly Station ");
        monthlyStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyStationActionPerformed(evt);
            }
        });

        annuallyOverall.setBackground(new java.awt.Color(0, 204, 204));
        annuallyOverall.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        annuallyOverall.setText("Annually Overall ");
        annuallyOverall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annuallyOverallActionPerformed(evt);
            }
        });

        annuallyStation.setBackground(new java.awt.Color(0, 204, 204));
        annuallyStation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        annuallyStation.setText("Annually Station");
        annuallyStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annuallyStationActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(0, 204, 204));
        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(annuallyOverall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthlyStation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(annuallyStation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monthlyOverall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(monthlyStation)
                .addGap(18, 18, 18)
                .addComponent(monthlyOverall)
                .addGap(18, 18, 18)
                .addComponent(annuallyOverall)
                .addGap(18, 18, 18)
                .addComponent(annuallyStation)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthlyOverallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyOverallActionPerformed
        // TODO add your handling code here:
        monthOverSelect sele = new monthOverSelect(this);
        sele.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_monthlyOverallActionPerformed

    private void monthlyStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyStationActionPerformed
        // TODO add your handling code here:
                
        monthStatSelect select = new monthStatSelect(this);
        select.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_monthlyStationActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        Functions funct = new Functions();
        funct.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void annuallyOverallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annuallyOverallActionPerformed
        // TODO add your handling code here:
        annOverSelect sele = new annOverSelect(this);
        sele.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_annuallyOverallActionPerformed

    private void annuallyStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annuallyStationActionPerformed
        // TODO add your handling code here:
        annStatSelect sele = new annStatSelect(this);
        sele.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_annuallyStationActionPerformed

    private JFrame parent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuallyOverall;
    private javax.swing.JButton annuallyStation;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton monthlyOverall;
    private javax.swing.JButton monthlyStation;
    // End of variables declaration//GEN-END:variables

}
